### ISSUE TITLE
[RS-71] Implementar todo el flujo de obtener coins por mergear un PR en Github

### ISSUE THREAD

**Issue by serudda** [serudda/reward-system#71]
### Descripción de la tarea

Una de las acciones que más valor deberían tener para obtener Indie Tokens, es cuando un miembro de la comunidad, toma un issue disponible, lo trabaja y lo concluye exitosamente. Al momento de ser mergeado ese Issue, se debería asignar una cantidad de Indie Token que debería tener asignada cada Issue (Esa asignación ya es subjetiva, cada quien determina cuanto valor tiene cada Issue.

Este debería ser el flujo a la hora de mergear un Issue exitosamente:
![_Github Reward_ flow](https://user-images.githubusercontent.com/10075532/225172879-3c86c284-2696-410b-b492-2d13339b7c2b.png)

-----

### Criterios de aceptación

- [ ] Definir y adjuntar user flow.
- [ ] Implementar el flujo definido en el criterio anterior.
- [ ] Dejar el comando funcionando en el server, hacer pruebas de todo el user flow.

**Comment by glrodasz** [comment]
¿Ya se tiene una solución para la relación del usuario con GitHub? o es parte de la tarea?

**Comment by serudda** [comment]
@glrodasz buen día pa. No entiendo a que te refieres con la relación del usuario con GitHub? Te refieres a la autenticación y los datos del user en base? Con respecto a GitHub?...

**Comment by serudda** [comment]
Ahh si si ya te entiendo @glrodasz 
Te explico... Cuando se mergee un PR exitosamente, es decir se Aprobó y se mergeo con develop... el o los Asignados recibirán la recompensa que estará configurada en los field custom del issue:

![Screenshot 2023-03-15 at 10 43 02 AM](https://user-images.githubusercontent.com/10075532/225363628-22507c53-7da1-42ec-8e87-ae52de9b6dce.png)

(Esto es algo nuevo que implemento Github hace un par de meses, los ProjectV2, donde te permite agregar field custom con la información que desees.

Entonces la idea es: Que exista un Github Action, que se dispare justo cuando sé cerro el Pul Request... ese Github Action, llame al endpoint de Github para obtener la siguiente información:
- User Asignee (username, githubId, name, email) y la recompensa o coins, que es el número que te señale en el screenshot anterior... Eso ya lo estamos haciendo, te dejo aquí él .yml del ese Github Action...

```yaml
name: Send Reward to the Assignee
on: push
jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Get Coins from Github Issue
        uses: octokit/graphql-action@v2.x
        id: get_coins
        with:
          query: |
            query GetCoinsAndAssigneeUser($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                issue(number: 71) {
                  assignees(first: 10) {
                    nodes {
                      id
                      avatarUrl
                      email
                      name
                      login
                    }
                  }
                  projectItems (first: 100) {
                    nodes {
                      fieldValueByName(name: "Reward") {
                        ... on ProjectV2ItemFieldNumberValue {
                          number
                        }
                      }
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest  release: ${{ steps.get_coins.outputs.data }}'"

      - name: Send Coins By Github Id
        uses: fjogeleit/http-request-action@v1
        id: send_coins
        with:
          url: 'https://localhost:3000/api/trpc/user.sendCoinsByGithubId'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"user": {"id": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].id }}", "login": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].login }}", "name": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].name }}", "email": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].email }}", "avatarUrl": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.assignees.nodes[0].avatarUrl }}"}, "coins": "${{ fromJson(steps.get_coins.outputs.data).repository.issue.projectItems.nodes[0].fieldValueByName.number }}}}'
```


Ese request al API de Github. Toca hacerlo a través de GraphQL, porque leyendo la documentación solo han implementado la obtención de los custom field, a través de su API GraphQL.

```js
          query GetCoinsAndAssigneeUser($owner:String!,$repo:String!) {
            repository(owner:$owner,name:$repo) {
              issue(number: 71) {
                assignees(first: 10) {
                  nodes {
                    id
                    avatarUrl
                    email
                    name
                    login
                  }
                }
                projectItems (first: 100) {
                  nodes {
                    fieldValueByName(name: "Reward") {
                      ... on ProjectV2ItemFieldNumberValue {
                        number
                      }
                    }
                  }
                }
              }
            }
          }
```

Eso ocurre en el step llamado: `Get Coins from Github Issue`


Ahora con lo que estoy teniendo problema, o no se como definir aun, es si mira el .yml, vas a ver un siguiente step llamado: `Send Coins By Github Id`

Es este toma el objeto resultante del GraphQL (eso ya lo valide, y esta tomando los datos del Assigne y el Reward) y envio eso a un endpoint de nuestra api que se encuentra en `packages/api/src/router/user.ts` y el endpoint se llama: `sendCoinsByGithubId`

El lio como ves en el .yml, es que hago POST a ese endpoint, pero no creo que vaya a funcionar, porque no le estoy pasando ningún tipo de Token de seguridad ni nada, entonces creo que se pueda comunicar así sé sencillo, y menos a través de un POST.

Asi que ahi estoy ahora bloqueado, porque no sé cómo hacer comunidad ese Step con el endpoint `sendCoinsByGithubId` ... Ese endpoint ya es el encargado de enviar esa data a la Base de Datos, y actualizar los coins del user.

Si quieres echarle un ojo, eso lo vas a encontrar en mi branch https://github.com/serudda/reward-system/tree/feature/RS-71-implement-github-flow

Para probarlo, lo que hice fue que por ahora el Github Action se dispare cuando se haga un push a este mismo branch... es decir, haces cualquier cambio, subes los cambios, y correría el Action, y ahí en consola podrías ver el log.

**Comment by korack93** [comment]
Esperando aportar un poco, @serudda veo que estás haciendo una petición https a localhost, en lugar de http, cosa que se debe solucionar cuando se cierre el issue #65, por el tema que se comentaba de que no se puede conectar los GitHub Actions a localhost. Además,  estuve probando con el trcp directamente con postman y la estructura que me aceptó fue con POST pero con el qry param batch ("api/trpc/user.sendCoinsByGithubId?batch=1") y con el siguiente body:
`{
    "0": {
        "json": {
            "user": {
            "id": "prueba",
            "login": "user_name",
            "name": "test_name",
            "email": "test@admin.com",
            "avatarUrl": "url.com"
            },
            "coins": 123
        }
    }
}`

Adjunto imagen con prueba.

<img width="1292" alt="Captura de Pantalla 2023-03-15 a la(s) 20 59 23" src="https://user-images.githubusercontent.com/26675064/225490219-2ee8b63c-f974-4250-8d77-b551bfd973c7.png">

**Comment by serudda** [comment]
uh interesante @korack93 que es eso de batch=1?

**Comment by korack93** [comment]
Según [la documentación](https://trpc.io/docs/links/httpBatchLink), esta función permite que se agrupen varias operaciones tRPC individuales en una sola solicitud HTTP. La cuál de utiliza en el archivo [utils/api.ts](https://github.com/serudda/reward-system/blob/feature/RS-71-implement-github-flow/apps/nextjs/src/utils/api.ts)

Por lo que veo, trpc utiliza api rest para pasar información entre el server y el front, pero realiza sus optimizaciones, en este caso, en lugar de una mutación estoy mandando el query que realiza el index.tsx de la app en nextjs, que se manda a través de un batch

## En la app de nextjs

<img width="1564" alt="Captura de Pantalla 2023-03-15 a la(s) 23 56 34" src="https://user-images.githubusercontent.com/26675064/225518291-bdd13cab-19fd-406a-8ab2-c4664199d401.png">

## En Postman

<img width="1058" alt="Captura de Pantalla 2023-03-15 a la(s) 23 57 17" src="https://user-images.githubusercontent.com/26675064/225518374-568b8cd0-6d4a-484c-aab7-e0358fc2bbb6.png">

**Comment by yebt** [comment]
Hope  @serudda, disculpe la interrupción, tratando de ayudar un poco, mientras se repara lo de Vercel y su incompatibilidad con bots de discord ( esto es causado porque Vercel genera '[serverless functions](https://vercel.com/docs/concepts/functions/serverless-functions)' y no servidores de escuha constante como se necesita para el bot de discord:  [Articulo](https://vercel.com/guides/can-i-deploy-discord-bots-to-vercel) ). podrías tratar de exponer tu `localhost` previo al deploy, te recomendaría estas 2 herramientas:

- [Expose.sh](https://expose.sh/)
- [LocalXpose](https://localxpose.io/blog/expose-localhost-to-internet)

La primera muestra de pronto una forma más sencilla. 
Al lograr exponer tu servicio de API con la url que se te genera, la colocas en el action que realiza la petición, remplazando a `localhost` y Github podrá acceder a tu servicio y almacenar el la cantidad de NDTokens

**Comment by serudda** [comment]
Ohh ok ok @korack93 entendido, muchas gracias.

Por otra parte acabo de tener avances, y si definitivamente validamos que los servicios tienen que estar desplegados.
Hice la prueba desplegando otro proyecto que tienen nuestra misma estructura, se deployo a Vercel, y apunto a uno de sus servicios:

`https://test-reward-system-nextjs.vercel.app/api/trpc/post.all?batch=1`

Y lo reconoce desde el archivo .yml:

Esto cuando corro el proyecto web:
![image](https://user-images.githubusercontent.com/10075532/225642012-4364f753-17e9-4661-814c-f99399ba150c.png)

Y esto cuando llamo el endpoint desde el github Action:
![image](https://user-images.githubusercontent.com/10075532/225642205-63a14bcc-581c-4f66-81af-e42cb189db9e.png)

**NOTA: Ignora ese error que está dando... eso es porque la tabla Post no existe.**

Asi que lo que voy a hacer es darle prioridad a la tarea https://github.com/serudda/reward-system/issues/65 para asi poder desplegar nuestra API, y con seguridad eso solucionara todo.

Gracias pa, te mantendre al tanto.

**Comment by serudda** [comment]
Uhhh @yebt muy buena idea, antes de deployar todo, voy a hacer eso que me dices de exponer el `localhost`.
Te cuento en un rato

**Comment by serudda** [comment]
``` yml
name: My Action
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: My step
        uses: octokit/graphql-action@v2.x
        with:
          graphql: 'query { viewer { login } }'
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
```
